[package]
name = "shuttlings-cch24"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = { version = "0.75.0", features = ["oapi"] }
shuttle-salvo = { version = "0.49.0", git = "https://github.com/Samyak2/shuttle", branch = "bump-salvo" }
shuttle-runtime = { version = "0.49.0", git = "https://github.com/Samyak2/shuttle", branch = "bump-salvo" }
tokio = "1.26.0"
serde = "1.0.216"
